export const FETCH_ALL_CHATS_REQUEST = Symbol('FETCH_ALL_CHATS_REQUEST');
export const FETCH_ALL_CHATS_SUCCESS = Symbol('FETCH_ALL_CHATS_SUCCESS');
export const FETCH_ALL_CHATS_FAILURE = Symbol('FETCH_ALL_CHATS_FAILURE');

export const FETCH_MY_CHATS_REQUEST = Symbol('FETCH_MY_CHATS_REQUEST');
export const FETCH_MY_CHATS_SUCCESS = Symbol('FETCH_MY_CHATS_SUCCESS');
export const FETCH_MY_CHATS_FAILURE = Symbol('FETCH_MY_CHATS_FAILURE');

export const FETCH_CHAT_REQUEST = Symbol('FETCH_CHAT_REQUEST');
export const FETCH_CHAT_SUCCESS = Symbol('FETCH_CHAT_SUCCESS');
export const FETCH_CHAT_FAILURE = Symbol('FETCH_CHAT_FAILURE');

export const SET_ACTIVE_CHAT = Symbol('SET_ACTIVE_CHAT');
export const UNSET_ACTIVE_CHAT = Symbol('UNSET_ACTIVE_CHAT');
