export const FETCH_ALL_CHATS_REQUEST = Symbol('FETCH_ALL_CHATS_REQUEST');
export const FETCH_ALL_CHATS_SUCCESS = Symbol('FETCH_ALL_CHATS_SUCCESS');
export const FETCH_ALL_CHATS_FAILURE = Symbol('FETCH_ALL_CHATS_FAILURE');

export const FETCH_MY_CHATS_REQUEST = Symbol('FETCH_MY_CHATS_REQUEST');
export const FETCH_MY_CHATS_SUCCESS = Symbol('FETCH_MY_CHATS_SUCCESS');
export const FETCH_MY_CHATS_FAILURE = Symbol('FETCH_MY_CHATS_FAILURE');

export const FETCH_CHAT_REQUEST = Symbol('FETCH_CHAT_REQUEST');
export const FETCH_CHAT_SUCCESS = Symbol('FETCH_CHAT_SUCCESS');
export const FETCH_CHAT_FAILURE = Symbol('FETCH_CHAT_FAILURE');

export const SET_ACTIVE_CHAT = Symbol('SET_ACTIVE_CHAT');
export const UNSET_ACTIVE_CHAT = Symbol('UNSET_ACTIVE_CHAT');

export const JOIN_CHAT_REQUEST = Symbol('JOIN_CHAT_REQUEST');
export const JOIN_CHAT_SUCCESS = Symbol('JOIN_CHAT_SUCCESS');
export const JOIN_CHAT_FAILURE = Symbol('JOIN_CHAT_FAILURE');

export const LEAVE_CHAT_REQUEST = Symbol('LEAVE_CHAT_REQUEST');
export const LEAVE_CHAT_SUCCESS = Symbol('LEAVE_CHAT_SUCCESS');
export const LEAVE_CHAT_FAILURE = Symbol('LEAVE_CHAT_FAILURE');

export const DELETE_CHAT_REQUEST = Symbol('DELETE_CHAT_REQUEST');
export const DELETE_CHAT_SUCCESS = Symbol('DELETE_CHAT_SUCCESS');
export const DELETE_CHAT_FAILURE = Symbol('DELETE_CHAT_FAILURE');

export const CREATE_CHAT_REQUEST = Symbol('CREATE_CHAT_REQUEST');
export const CREATE_CHAT_SUCCESS = Symbol('CREATE_CHAT_SUCCESS');
export const CREATE_CHAT_FAILURE = Symbol('CREATE_CHAT_FAILURE');
